services:
  - type: web
    name: trustbank
    env: python
    buildCommand: ""
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: FLASK_SECRET_KEY
        value: your-secret-key-here
